-- Catalog spots stored in the database: Green Coffee and the Digos City coffee shops, with their hours and photo
-- paths (the photo files are served by the site from /spots/). Generated by scripts/generate-cafes-seed.mjs from
-- src/data; do not edit by hand, change the data and regenerate.
--
-- Safe to run more than once: rows are upserted by id. Visitor-driven counts (save_count, view_count) and the admin's
-- verified flag are never overwritten. The ids match the ones the app already used, so saved spots keep working.

-- 1. A spot can have no price listed (0); the app then shows no price and never calls the spot cheap.
alter table public.cafes drop constraint if exists cafes_price_level_check;
alter table public.cafes add constraint cafes_price_level_check check (price_level between 0 and 3);

-- 2. The spots.
insert into public.cafes (id, handle, name, is_roastery, city, district, address, lat, lng, images, logo_url, description, signature, menu, amenities, wifi_mbps, brew_methods, price_level, hours, vibe_tags, verified)
values
  ('curated-green-coffee-digos', 'green-coffee-digos', 'Green Coffee', false, 'Digos City', 'Digos', 'Quezon Avenue corner Rizal Avenue, Digos Junction Road, Digos City, Davao del Sur', 6.7548589, 125.3555501, array['/spots/green-coffee-digos/storefront.webp', '/spots/green-coffee-digos/interior.webp', '/spots/green-coffee-digos/grinder.webp', '/spots/green-coffee-digos/planters.webp']::text[], '/spots/green-coffee-digos/storefront.webp', 'Corner coffee shop on Quezon Avenue at Rizal Avenue, by the Digos junction. A glass-front dining room with a mezzanine upstairs and a covered terrace out front, open from 7 in the morning until 2 at night every day.', '', '[{"name":"Caramel Macchiato","price":220,"category":"Espresso Bar"},{"name":"Caramel Blended Coffee","price":215,"category":"Signature"},{"name":"Cheezy Pork Floss","price":145,"category":"Pastry"}]'::jsonb, array['outdoor', 'lateNight']::text[], 0, '{}'::text[], 2, '{"Monday":{"open":"07:00","close":"02:00"},"Tuesday":{"open":"07:00","close":"02:00"},"Wednesday":{"open":"07:00","close":"02:00"},"Thursday":{"open":"07:00","close":"02:00"},"Friday":{"open":"07:00","close":"02:00"},"Saturday":{"open":"07:00","close":"02:00"},"Sunday":{"open":"07:00","close":"02:00"}}'::jsonb, array['Open late', 'Terrace seating']::text[], false),
  ('osm-w1431054042', 'g-co-cafe-osm-w1431054042', 'G&Co. Cafe', false, 'Digos City', 'Digos', 'Quezon Avenue, Digos City, Davao del Sur', 6.760166, 125.347892, array['/spots/g-co-cafe-digos/photo-1.webp']::text[], '/spots/g-co-cafe-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":"10:00","close":"22:00"},"Tuesday":{"open":"10:00","close":"22:00"},"Wednesday":{"open":"10:00","close":"22:00"},"Thursday":{"open":"10:00","close":"22:00"},"Friday":{"open":"10:00","close":"22:00"},"Saturday":{"open":"10:00","close":"22:00"},"Sunday":{"open":"10:00","close":"22:00"}}'::jsonb, '{}'::text[], false),
  ('osm-n13308179172', 'lil-ben-coffee-house-osm-n13308179172', 'Lil'' Ben Coffee House', false, 'Digos City', 'Digos', 'Santa Ana Street, Digos City, Davao del Sur', 6.76256, 125.336229, array['/spots/lil-ben-coffee-house-digos/photo-1.webp']::text[], '/spots/lil-ben-coffee-house-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":"13:00","close":"22:00"},"Tuesday":{"open":"13:00","close":"22:00"},"Wednesday":{"open":"13:00","close":"22:00"},"Thursday":{"open":"13:00","close":"22:00"},"Friday":{"open":"13:00","close":"22:00"},"Saturday":{"open":"13:00","close":"22:00"},"Sunday":{"open":"13:00","close":"22:00"}}'::jsonb, '{}'::text[], false),
  ('osm-n13168672184', 'cafe-vicente-osm-n13168672184', 'Café Vicente', false, 'Digos City', 'Digos', 'Estrada 5th, Digos City, Davao del Sur', 6.753013, 125.348828, array['/spots/cafe-vicente-digos/photo-1.webp']::text[], '/spots/cafe-vicente-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":"10:00","close":"20:00"},"Tuesday":{"open":"10:00","close":"20:00"},"Wednesday":{"open":"10:00","close":"20:00"},"Thursday":{"open":"10:00","close":"20:00"},"Friday":{"open":"08:30","close":"21:00"},"Saturday":{"open":"08:30","close":"21:00"},"Sunday":{"open":"10:00","close":"20:00"}}'::jsonb, '{}'::text[], false),
  ('osm-n13049364628', 'cely-s-cafe-osm-n13049364628', 'Cely''s Cafe', false, 'Digos City', 'Digos', 'Rizal Avenue, Digos City, Davao del Sur', 6.75342, 125.356339, array['/spots/cely-s-cafe-digos/photo-1.webp']::text[], '/spots/cely-s-cafe-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":null,"close":null},"Tuesday":{"open":null,"close":null},"Wednesday":{"open":null,"close":null},"Thursday":{"open":null,"close":null},"Friday":{"open":null,"close":null},"Saturday":{"open":null,"close":null},"Sunday":{"open":null,"close":null}}'::jsonb, '{}'::text[], false),
  ('digos-the-tipsy-butter', 'the-tipsy-butter-digos-the-tipsy-butter', 'The Tipsy Butter', false, 'Digos City', 'Digos', 'Roxas Extension, Digos City, Davao del Sur', 6.749913, 125.344984, array['/spots/the-tipsy-butter-digos/photo-1.webp']::text[], '/spots/the-tipsy-butter-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":"09:00","close":"19:00"},"Tuesday":{"open":"09:00","close":"19:00"},"Wednesday":{"open":"09:00","close":"19:00"},"Thursday":{"open":"09:00","close":"19:00"},"Friday":{"open":"09:00","close":"19:00"},"Saturday":{"open":"09:00","close":"19:00"},"Sunday":{"open":"09:00","close":"17:00"}}'::jsonb, '{}'::text[], false),
  ('digos-infinitea', 'infinitea-digos-infinitea', 'Infinitea', false, 'Digos City', 'Digos', 'Quirino, Digos City, Davao del Sur', 6.758388, 125.346766, array['/spots/infinitea-digos/photo-1.webp']::text[], '/spots/infinitea-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":null,"close":null},"Tuesday":{"open":null,"close":null},"Wednesday":{"open":null,"close":null},"Thursday":{"open":null,"close":null},"Friday":{"open":null,"close":null},"Saturday":{"open":null,"close":null},"Sunday":{"open":null,"close":null}}'::jsonb, '{}'::text[], false),
  ('digos-kaffeeneology', 'kaffeeneology-digos-kaffeeneology', 'Kaffeeneology', false, 'Digos City', 'Digos', 'Roxas Extension, Digos City, Davao del Sur', 6.749928, 125.345555, array['/spots/kaffeeneology-digos/photo-1.webp']::text[], '/spots/kaffeeneology-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":"10:00","close":"01:00"},"Tuesday":{"open":"10:00","close":"01:00"},"Wednesday":{"open":"10:00","close":"01:00"},"Thursday":{"open":"10:00","close":"01:00"},"Friday":{"open":"10:00","close":"01:00"},"Saturday":{"open":"10:00","close":"01:00"},"Sunday":{"open":"13:00","close":"22:00"}}'::jsonb, '{}'::text[], false),
  ('digos-cool-brews', 'cool-brews-digos-cool-brews', 'Cool Brews', false, 'Digos City', 'Digos', 'Estrada 3rd, Digos City, Davao del Sur', 6.754738, 125.352391, array['/spots/cool-brews-digos/photo-1.webp']::text[], '/spots/cool-brews-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":"15:00","close":"22:00"},"Tuesday":{"open":"15:00","close":"22:00"},"Wednesday":{"open":"15:00","close":"22:00"},"Thursday":{"open":"15:00","close":"22:00"},"Friday":{"open":"15:00","close":"22:00"},"Saturday":{"open":"15:00","close":"22:00"},"Sunday":{"open":"15:00","close":"22:00"}}'::jsonb, '{}'::text[], false),
  ('digos-the-nook', 'the-nook-digos-the-nook', 'The Nook', false, 'Digos City', 'Digos', 'Mabini 3rd, Digos City, Davao del Sur', 6.740396, 125.358828, array['/spots/the-nook-digos/photo-1.webp']::text[], '/spots/the-nook-digos/photo-1.webp', '', '', '[]'::jsonb, '{}'::text[], 0, '{}'::text[], 0, '{"Monday":{"open":"10:00","close":"22:00"},"Tuesday":{"open":"10:00","close":"22:00"},"Wednesday":{"open":"10:00","close":"22:00"},"Thursday":{"open":"10:00","close":"22:00"},"Friday":{"open":"10:00","close":"22:00"},"Saturday":{"open":"10:00","close":"22:00"},"Sunday":{"open":"13:00","close":"22:00"}}'::jsonb, '{}'::text[], false)
on conflict (id) do update set
  handle = excluded.handle,
  name = excluded.name,
  is_roastery = excluded.is_roastery,
  city = excluded.city,
  district = excluded.district,
  address = excluded.address,
  lat = excluded.lat,
  lng = excluded.lng,
  images = excluded.images,
  logo_url = excluded.logo_url,
  description = excluded.description,
  signature = excluded.signature,
  menu = excluded.menu,
  amenities = excluded.amenities,
  wifi_mbps = excluded.wifi_mbps,
  brew_methods = excluded.brew_methods,
  price_level = excluded.price_level,
  hours = excluded.hours,
  vibe_tags = excluded.vibe_tags;

-- Check: this should return 10
-- select count(*) from public.cafes where id like 'osm-%' or id like 'digos-%' or id like 'curated-%';
